// generated by MetaMate
export const industries = [
    {
      value: "Technology",
      label: "Technology",
    },
    {
      value: "Information Technology",
      label: "Information Technology",
    },
    {
      value: "Software Development",
      label: "Software Development",
    },
    {
      value: "Cybersecurity",
      label: "Cybersecurity",
    },
    {
      value: "Artificial Intelligence",
      label: "Artificial Intelligence",
    },
    {
      value: "Finance",
      label: "Finance",
    },
    {
      value: "Banking",
      label: "Banking",
    },
    {
      value: "Investment Management",
      label: "Investment Management",
    },
    {
      value: "Insurance",
      label: "Insurance",
    },
    {
      value: "Fintech",
      label: "Fintech",
    },
    {
      value: "Accounting",
      label: "Accounting",
    },
    {
      value: "Healthcare",
      label: "Healthcare",
    },
    {
      value: "Pharmaceuticals",
      label: "Pharmaceuticals",
    },
    {
      value: "Biotechnology",
      label: "Biotechnology",
    },
    {
      value: "Medical Devices",
      label: "Medical Devices",
    },
    {
      value: "Education",
      label: "Education",
    },
    {
      value: "Higher Education",
      label: "Higher Education",
    },
    {
      value: "E-commerce",
      label: "E-commerce",
    },
    {
      value: "Retail",
      label: "Retail",
    },
    {
      value: "Consumer Goods",
      label: "Consumer Goods",
    },
    {
      value: "Manufacturing",
      label: "Manufacturing",
    },
    {
      value: "Automotive",
      label: "Automotive",
    },
    {
      value: "Aerospace",
      label: "Aerospace",
    },
    {
      value: "Energy",
      label: "Energy",
    },
    {
      value: "Renewable Energy",
      label: "Renewable Energy",
    },
    {
      value: "Oil & Gas",
      label: "Oil & Gas",
    },
    {
      value: "Utilities",
      label: "Utilities",
    },
    {
      value: "Construction",
      label: "Construction",
    },
    {
      value: "Real Estate",
      label: "Real Estate",
    },
    {
      value: "Hospitality",
      label: "Hospitality",
    },
    {
      value: "Travel & Tourism",
      label: "Travel & Tourism",
    },
    {
      value: "Media & Entertainment",
      label: "Media & Entertainment",
    },
    {
      value: "Telecommunications",
      label: "Telecommunications",
    },
    {
      value: "Agriculture",
      label: "Agriculture",
    },
    {
      value: "Food & Beverage",
      label: "Food & Beverage",
    },
    {
      value: "Logistics & Supply Chain",
      label: "Logistics & Supply Chain",
    },
    {
      value: "Transportation",
      label: "Transportation",
    },
    {
      value: "Legal Services",
      label: "Legal Services",
    },
    {
      value: "Consulting",
      label: "Consulting",
    },
    {
      value: "Non-Profit",
      label: "Non-Profit",
    },
    {
      value: "Government & Public Sector",
      label: "Government & Public Sector",
    },
    {
      value: "Human Resources",
      label: "Human Resources",
    },
    {
      value: "Marketing & Advertising",
      label: "Marketing & Advertising",
    },
    {
      value: "Environmental Services",
      label: "Environmental Services",
    },
    {
      value: "Social Media",
      label: "Social Media",
    },
    {
      value: "Gaming",
      label: "Gaming",
    },
    {
      value: "Space Exploration",
      label: "Space Exploration",
    },
    {
      value: "Electric Vehicles",
      label: "Electric Vehicles",
    },
    {
      value: "Smart Home Technology",
      label: "Smart Home Technology",
    },
    {
      value: "Virtual Reality (VR) and Augmented Reality (AR)",
      label: "Virtual Reality (VR) and Augmented Reality (AR)",
    }
  ];
